#include "berialdraw_imp.hpp"
#include "samples/samples.hpp"

namespace berialdraw
{
	void test_widget()
	{
		tools_test2();
	#if _DEBUG
		UIManager::styles()->style("test");
		UIManager::colors()->appearance("test_light");

		Button::test();

		// Widgets
		Icon::test();
		ProgressBar::test();
		Slider::test();
		Edit::test();
		Switch::test();
		ScrollView::test();
		Button::test();
		Keyboard::test();
		Canvas::test();
		Pane::test();
		Label::test();
		Window::test();

		// Shapes
		Rect::test();
		Pie::test();
		Text::test();
		LineChart::test();
		Compass::test();
		Line::test();
		Marker::test();
		PolyLines::test();
		Polygon::test();	
		Region::test();
		Outline::test();
		Font::test();
		Colors::test();
	#endif
	}
	void test_samples()
	{
		static bool done = false;
		if (done == false)
		{
			done = true;

			String script(
			"["
				"{'type':'snapshot','filename':'test/out/sample_icon_list_%d.svg'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'snapshot','filename':'test/out/sample_buton_%d.svg'},"
				"{'type':'touch','x': 81,'y': 93,'state':'down'},"
				"{'type':'touch','x': 81,'y': 93,'state':'up'},"
				"{'type':'touch','x':229,'y':134,'state':'down'},"
				"{'type':'touch','x':229,'y':134,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'touch','x': 59,'y': 26,'state':'down'},"
				"{'type':'touch','x': 59,'y': 26,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_canvas_%d.svg'},"
				"{'type':'touch','x':181,'y': 81,'state':'down'},"
				"{'type':'touch','x':181,'y': 81,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'touch','x': 43,'y': 24,'state':'down'},"
				"{'type':'touch','x': 43,'y': 24,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_column_%d.svg'},"
				"{'type':'touch','x':296,'y': 68,'state':'down'},"
				"{'type':'touch','x':296,'y': 68,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':335,'y':456,'state':'down'},"
				"{'type':'touch','x':333,'y':440,'state':'move'},"
				"{'type':'touch','x':315,'y':372,'state':'move'},"
				"{'type':'touch','x':299,'y':278,'state':'move'},"
				"{'type':'touch','x':293,'y':199,'state':'move'},"
				"{'type':'touch','x':288,'y':159,'state':'move'},"
				"{'type':'touch','x':284,'y':135,'state':'move'},"
				"{'type':'touch','x':284,'y':128,'state':'move'},"
				"{'type':'touch','x':285,'y':124,'state':'move'},"
				"{'type':'touch','x':285,'y':120,'state':'move'},"
				"{'type':'touch','x':287,'y':111,'state':'move'},"
				"{'type':'touch','x':289,'y': 99,'state':'move'},"
				"{'type':'touch','x':289,'y': 95,'state':'move'},"
				"{'type':'touch','x':289,'y': 95,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'touch','x': 59,'y': 15,'state':'down'},"
				"{'type':'touch','x': 59,'y': 15,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_edit_%d.svg'},"
				"{'type':'touch','x':401,'y': 90,'state':'down'},"
				"{'type':'touch','x':401,'y': 90,'state':'up'},"
				"{'type':'key','key': 72,'state':'down','modifier':'shift','character':'H'},"
				"{'type':'key','key': 72,'state':'up'  ,'modifier':'shift','character':'H'},"
				"{'type':'key','key':101,'state':'down','modifier':''     ,'character':'e'},"
				"{'type':'key','key':101,'state':'up'  ,'modifier':''     ,'character':'e'},"
				"{'type':'key','key':108,'state':'down','modifier':''     ,'character':'l'},"
				"{'type':'key','key':108,'state':'up'  ,'modifier':''     ,'character':'l'},"
				"{'type':'key','key':108,'state':'down','modifier':''     ,'character':'l'},"
				"{'type':'key','key':108,'state':'up'  ,'modifier':''     ,'character':'l'},"
				"{'type':'key','key':111,'state':'down','modifier':''     ,'character':'o'},"
				"{'type':'key','key':111,'state':'up'  ,'modifier':''     ,'character':'o'},"
				"{'type':'key','key': 32,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key': 32,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'key','key': 87,'state':'down','modifier':'shift','character':'W'},"
				"{'type':'key','key':119,'state':'up'  ,'modifier':''     ,'character':'w'},"
				"{'type':'key','key':111,'state':'down','modifier':''     ,'character':'o'},"
				"{'type':'key','key':111,'state':'up'  ,'modifier':''     ,'character':'o'},"
				"{'type':'key','key':114,'state':'down','modifier':''     ,'character':'r'},"
				"{'type':'key','key':114,'state':'up'  ,'modifier':''     ,'character':'r'},"
				"{'type':'key','key':108,'state':'down','modifier':''     ,'character':'l'},"
				"{'type':'key','key':108,'state':'up'  ,'modifier':''     ,'character':'l'},"
				"{'type':'key','key':100,'state':'down','modifier':''     ,'character':'d'},"
				"{'type':'key','key':100,'state':'up'  ,'modifier':''     ,'character':'d'},"
				"{'type':'touch','x':261,'y': 92,'state':'down'},"
				"{'type':'touch','x':241,'y': 90,'state':'move'},"
				"{'type':'touch','x':141,'y': 88,'state':'move'},"
				"{'type':'touch','x': 53,'y': 89,'state':'move'},"
				"{'type':'touch','x': 27,'y': 93,'state':'move'},"
				"{'type':'touch','x':32764,'y': 93,'state':'move'},"
				"{'type':'touch','x':32764,'y': 93,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':151,'y': 87,'state':'down'},"
				"{'type':'touch','x':144,'y': 87,'state':'move'},"
				"{'type':'touch','x': 92,'y': 87,'state':'move'},"
				"{'type':'touch','x': 26,'y': 87,'state':'move'},"
				"{'type':'touch','x':  3,'y': 90,'state':'move'},"
				"{'type':'touch','x':32765,'y': 89,'state':'move'},"
				"{'type':'touch','x':  1,'y': 87,'state':'move'},"
				"{'type':'touch','x':  4,'y': 85,'state':'move'},"
				"{'type':'touch','x':  8,'y': 83,'state':'move'},"
				"{'type':'touch','x': 12,'y': 81,'state':'move'},"
				"{'type':'touch','x': 11,'y': 82,'state':'move'},"
				"{'type':'touch','x': 11,'y': 82,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'key','key':  9,'state':'down','modifier':''     ,'character':'I'},"
				"{'type':'key','key':  9,'state':'up'  ,'modifier':''     ,'character':'I'},"
				"{'type':'key','key': 49,'state':'down','modifier':''     ,'character':'1'},"
				"{'type':'key','key': 49,'state':'up'  ,'modifier':''     ,'character':'1'},"
				"{'type':'key','key': 50,'state':'down','modifier':''     ,'character':'2'},"
				"{'type':'key','key': 50,'state':'up'  ,'modifier':''     ,'character':'2'},"
				"{'type':'key','key': 51,'state':'down','modifier':''     ,'character':'3'},"
				"{'type':'key','key': 51,'state':'up'  ,'modifier':''     ,'character':'3'},"
				"{'type':'key','key': 52,'state':'down','modifier':''     ,'character':'4'},"
				"{'type':'key','key': 52,'state':'up'  ,'modifier':''     ,'character':'4'},"
				"{'type':'key','key': 53,'state':'down','modifier':''     ,'character':'5'},"
				"{'type':'key','key': 53,'state':'up'  ,'modifier':''     ,'character':'5'},"
				"{'type':'key','key': 57,'state':'down','modifier':''     ,'character':'9'},"
				"{'type':'key','key': 57,'state':'up'  ,'modifier':''     ,'character':'9'},"
				"{'type':'key','key':  9,'state':'down','modifier':''     ,'character':'I'},"
				"{'type':'key','key':  9,'state':'up'  ,'modifier':''     ,'character':'I'},"
				"{'type':'key','key': 45,'state':'down','modifier':''     ,'character':'-'},"
				"{'type':'key','key': 45,'state':'up'  ,'modifier':''     ,'character':'-'},"
				"{'type':'key','key': 49,'state':'down','modifier':''     ,'character':'1'},"
				"{'type':'key','key': 49,'state':'up'  ,'modifier':''     ,'character':'1'},"
				"{'type':'key','key': 48,'state':'down','modifier':''     ,'character':'0'},"
				"{'type':'key','key': 48,'state':'up'  ,'modifier':''     ,'character':'0'},"
				"{'type':'key','key': 46,'state':'down','modifier':'shift','character':'.'},"
				"{'type':'key','key': 46,'state':'up'  ,'modifier':''     ,'character':'.'},"
				"{'type':'key','key': 50,'state':'down','modifier':''     ,'character':'2'},"
				"{'type':'key','key': 50,'state':'up'  ,'modifier':''     ,'character':'2'},"
				"{'type':'key','key': 53,'state':'down','modifier':''     ,'character':'5'},"
				"{'type':'key','key': 53,'state':'up'  ,'modifier':''     ,'character':'5'},"
				"{'type':'key','key':  9,'state':'down','modifier':''     ,'character':'I'},"
				"{'type':'key','key':  9,'state':'up'  ,'modifier':''     ,'character':'I'},"
				"{'type':'key','key': 49,'state':'down','modifier':''     ,'character':'1'},"
				"{'type':'key','key': 49,'state':'up'  ,'modifier':''     ,'character':'1'},"
				"{'type':'key','key': 57,'state':'down','modifier':''     ,'character':'9'},"
				"{'type':'key','key': 57,'state':'up'  ,'modifier':''     ,'character':'9'},"
				"{'type':'key','key': 50,'state':'down','modifier':''     ,'character':'2'},"
				"{'type':'key','key': 50,'state':'up'  ,'modifier':''     ,'character':'2'},"
				"{'type':'key','key': 49,'state':'down','modifier':''     ,'character':'1'},"
				"{'type':'key','key': 49,'state':'up'  ,'modifier':''     ,'character':'1'},"
				"{'type':'key','key': 54,'state':'down','modifier':''     ,'character':'6'},"
				"{'type':'key','key': 54,'state':'up'  ,'modifier':''     ,'character':'6'},"
				"{'type':'key','key': 57,'state':'down','modifier':''     ,'character':'9'},"
				"{'type':'key','key': 57,'state':'up'  ,'modifier':''     ,'character':'9'},"
				"{'type':'key','key': 46,'state':'down','modifier':'shift','character':'.'},"
				"{'type':'key','key': 46,'state':'up'  ,'modifier':''     ,'character':'.'},"
				"{'type':'key','key': 49,'state':'down','modifier':''     ,'character':'1'},"
				"{'type':'key','key': 49,'state':'up'  ,'modifier':''     ,'character':'1'},"
				"{'type':'key','key': 46,'state':'down','modifier':'shift','character':'.'},"
				"{'type':'key','key': 46,'state':'up'  ,'modifier':'shift','character':'.'},"
				"{'type':'key','key': 49,'state':'down','modifier':''     ,'character':'1'},"
				"{'type':'key','key': 49,'state':'up'  ,'modifier':''     ,'character':'1'},"
				"{'type':'key','key':  9,'state':'down','modifier':''     ,'character':'I'},"
				"{'type':'key','key':  9,'state':'up'  ,'modifier':''     ,'character':'I'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x': 29,'y': 17,'state':'down'},"
				"{'type':'touch','x': 29,'y': 17,'state':'up'},"

				"{'type':'touch','x': 71,'y':221,'state':'down'},"
				"{'type':'touch','x': 71,'y':221,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_grid_%d.svg'},"
				"{'type':'touch','x':360,'y':453,'state':'down'},"
				"{'type':'touch','x':358,'y':447,'state':'move'},"
				"{'type':'touch','x':313,'y':318,'state':'move'},"
				"{'type':'touch','x':313,'y':193,'state':'move'},"
				"{'type':'touch','x':317,'y':158,'state':'move'},"
				"{'type':'touch','x':319,'y':143,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'touch','x': 48,'y': 14,'state':'down'},"
				"{'type':'touch','x': 48,'y': 14,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_icon_%d.svg'},"
				"{'type':'touch','x':196,'y':211,'state':'down'},"
				"{'type':'touch','x':196,'y':211,'state':'up'},"
				"{'type':'touch','x':248,'y': 77,'state':'down'},"
				"{'type':'touch','x':248,'y': 77,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'touch','x': 53,'y': 27,'state':'down'},"
				"{'type':'touch','x': 52,'y': 26,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_keyboard_%d.svg'},"
				"{'type':'touch','x':322,'y':214,'state':'down'},"
				"{'type':'touch','x':322,'y':214,'state':'up'},"
				"{'type':'touch','x':251,'y':351,'state':'down'},"
				"{'type':'touch','x':251,'y':351,'state':'up'},"
				"{'type':'touch','x':120,'y':298,'state':'down'},"
				"{'type':'touch','x':120,'y':298,'state':'up'},"
				"{'type':'touch','x':412,'y':344,'state':'down'},"
				"{'type':'touch','x':412,'y':345,'state':'up'},"
				"{'type':'touch','x':412,'y':345,'state':'down'},"
				"{'type':'touch','x':412,'y':345,'state':'up'},"
				"{'type':'touch','x':412,'y':292,'state':'down'},"
				"{'type':'touch','x':412,'y':292,'state':'up'},"
				"{'type':'touch','x':325,'y':458,'state':'down'},"
				"{'type':'touch','x':325,'y':458,'state':'up'},"
				"{'type':'touch','x':450,'y':437,'state':'down'},"
				"{'type':'touch','x':450,'y':437,'state':'up'},"
				"{'type':'touch','x': 94,'y':113,'state':'down'},"
				"{'type':'touch','x': 94,'y':113,'state':'up'},"
				"{'type':'touch','x': 94,'y':113,'state':'down'},"
				"{'type':'touch','x': 92,'y':113,'state':'move'},"
				"{'type':'touch','x': 81,'y':113,'state':'move'},"
				"{'type':'touch','x': 69,'y':111,'state':'move'},"
				"{'type':'touch','x': 46,'y': 97,'state':'move'},"
				"{'type':'touch','x': 33,'y': 88,'state':'move'},"
				"{'type':'touch','x': 22,'y': 80,'state':'move'},"
				"{'type':'touch','x': 18,'y': 79,'state':'move'},"
				"{'type':'touch','x': 11,'y': 78,'state':'move'},"
				"{'type':'touch','x': 11,'y': 78,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'touch','x': 39,'y': 28,'state':'down'},"
				"{'type':'touch','x': 39,'y': 28,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_label_%d.svg'},"
				"{'type':'touch','x':388,'y':231,'state':'down'},"
				"{'type':'touch','x':388,'y':230,'state':'up'},"
				"{'type':'touch','x':379,'y':230,'state':'down'},"
				"{'type':'touch','x':379,'y':230,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'touch','x': 62,'y': 12,'state':'down'},"
				"{'type':'touch','x': 62,'y': 12,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_pane_%d.svg'},"
				"{'type':'touch','x': 62,'y':339,'state':'down'},"
				"{'type':'touch','x': 62,'y':339,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'key','key':  9,'state':'down','modifier':''     ,'character':'I'},"
				"{'type':'key','key':  9,'state':'up'  ,'modifier':''     ,'character':'I'},"
				"{'type':'key','key':  9,'state':'down','modifier':''     ,'character':'I'},"
				"{'type':'key','key':  9,'state':'up'  ,'modifier':''     ,'character':'I'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'touch','x': 39,'y': 17,'state':'down'},"
				"{'type':'touch','x': 39,'y': 17,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_progress_%d.svg'},"
				"{'type':'touch','x':197,'y':327,'state':'down'},"
				"{'type':'touch','x':197,'y':327,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':164,'y':453,'state':'down'},"
				"{'type':'touch','x':167,'y':452,'state':'move'},"
				"{'type':'touch','x':222,'y':448,'state':'move'},"
				"{'type':'touch','x':305,'y':442,'state':'move'},"
				"{'type':'touch','x':365,'y':442,'state':'move'},"
				"{'type':'touch','x':369,'y':443,'state':'move'},"
				"{'type':'touch','x':368,'y':443,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'touch','x': 33,'y': 10,'state':'down'},"
				"{'type':'touch','x': 33,'y': 10,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_row_%d.svg'},"
				"{'type':'touch','x':315,'y':332,'state':'down'},"
				"{'type':'touch','x':315,'y':332,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':459,'y':321,'state':'down'},"
				"{'type':'touch','x':458,'y':321,'state':'move'},"
				"{'type':'touch','x':237,'y':319,'state':'move'},"
				"{'type':'touch','x': 61,'y':318,'state':'move'},"
				"{'type':'touch','x': 38,'y':318,'state':'move'},"
				"{'type':'touch','x': 37,'y':319,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'touch','x': 26,'y': 14,'state':'down'},"
				"{'type':'touch','x': 26,'y': 14,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_scroll_%d.svg'},"
				"{'type':'touch','x':424,'y':379,'state':'down'},"
				"{'type':'touch','x':423,'y':378,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':456,'y':200,'state':'down'},"
				"{'type':'touch','x':435,'y':200,'state':'move'},"
				"{'type':'touch','x':164,'y':199,'state':'move'},"
				"{'type':'touch','x': 50,'y':196,'state':'move'},"
				"{'type':'touch','x': 17,'y':193,'state':'move'},"
				"{'type':'touch','x': 15,'y':193,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':259,'y':428,'state':'down'},"
				"{'type':'touch','x':260,'y':344,'state':'move'},"
				"{'type':'touch','x':265,'y':143,'state':'move'},"
				"{'type':'touch','x':266,'y': 74,'state':'move'},"
				"{'type':'touch','x':266,'y': 68,'state':'move'},"
				"{'type':'touch','x':265,'y': 69,'state':'move'},"
				"{'type':'touch','x':265,'y': 69,'state':'up'},"
				"{'type':'touch','x':265,'y': 69,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'touch','x': 57,'y': 14,'state':'down'},"
				"{'type':'touch','x': 57,'y': 14,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_slider_%d.svg'},"
				"{'type':'touch','x': 69,'y':429,'state':'down'},"
				"{'type':'touch','x': 69,'y':429,'state':'up'},"
				"{'type':'touch','x':114,'y':196,'state':'down'},"
				"{'type':'touch','x':114,'y':197,'state':'move'},"
				"{'type':'touch','x':114,'y':214,'state':'move'},"
				"{'type':'touch','x':116,'y':279,'state':'move'},"
				"{'type':'touch','x':119,'y':296,'state':'move'},"
				"{'type':'touch','x':123,'y':313,'state':'move'},"
				"{'type':'touch','x':126,'y':318,'state':'move'},"
				"{'type':'touch','x':126,'y':318,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'touch','x': 27,'y': 23,'state':'down'},"
				"{'type':'touch','x': 27,'y': 23,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_switch_%d.svg'},"
				"{'type':'touch','x':181,'y':450,'state':'down'},"
				"{'type':'touch','x':181,'y':450,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':246,'y': 86,'state':'down'},"
				"{'type':'touch','x':246,'y': 86,'state':'up'},"
				"{'type':'touch','x':273,'y':191,'state':'down'},"
				"{'type':'touch','x':273,'y':191,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'touch','x': 51,'y': 22,'state':'down'},"
				"{'type':'touch','x': 51,'y': 22,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_window_%d.svg'},"
				"{'type':'touch','x':298,'y':460,'state':'down'},"
				"{'type':'touch','x':298,'y':460,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'touch','x': 45,'y': 30,'state':'down'},"
				"{'type':'touch','x': 45,'y': 30,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_speed_%d.svg'},"
				"{'type':'touch','x':433,'y':452,'state':'down'},"
				"{'type':'touch','x':433,'y':452,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x': 32,'y':451,'state':'down'},"
				"{'type':'touch','x': 46,'y':451,'state':'move'},"
				"{'type':'touch','x':126,'y':447,'state':'move'},"
				"{'type':'touch','x':253,'y':447,'state':'move'},"
				"{'type':'touch','x':285,'y':453,'state':'move'},"
				"{'type':'touch','x':292,'y':452,'state':'move'},"
				"{'type':'touch','x':297,'y':452,'state':'move'},"
				"{'type':'touch','x':317,'y':452,'state':'move'},"
				"{'type':'touch','x':319,'y':452,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"

				"{'type':'touch','x': 54,'y': 20,'state':'down'},"
				"{'type':'touch','x': 54,'y': 20,'state':'up'},"

				"{'type':'snapshot','filename':'test/out/sample_theme_%d.svg'},"
				"{'type':'touch','x':313,'y':356,'state':'down'},"
				"{'type':'touch','x':313,'y':347,'state':'move'},"
				"{'type':'touch','x':306,'y':287,'state':'move'},"
				"{'type':'touch','x':300,'y':217,'state':'move'},"
				"{'type':'touch','x':300,'y':174,'state':'move'},"
				"{'type':'touch','x':300,'y':157,'state':'move'},"
				"{'type':'touch','x':300,'y':150,'state':'move'},"
				"{'type':'touch','x':300,'y':145,'state':'move'},"
				"{'type':'touch','x':300,'y':139,'state':'move'},"
				"{'type':'touch','x':300,'y':133,'state':'up'},"
				"{'type':'touch','x':300,'y':134,'state':'move'},"
				"{'type':'touch','x': 61,'y':405,'state':'down'},"
				"{'type':'touch','x': 61,'y':405,'state':'up'},"
				"{'type':'touch','x': 10,'y': 84,'state':'down'},"
				"{'type':'touch','x': 10,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x': 36,'y': 83,'state':'down'},"
				"{'type':'touch','x': 36,'y': 83,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x': 60,'y': 84,'state':'down'},"
				"{'type':'touch','x': 60,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x': 85,'y': 83,'state':'down'},"
				"{'type':'touch','x': 85,'y': 83,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':107,'y': 84,'state':'down'},"
				"{'type':'touch','x':107,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':133,'y': 84,'state':'down'},"
				"{'type':'touch','x':133,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':156,'y': 84,'state':'down'},"
				"{'type':'touch','x':156,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':180,'y': 84,'state':'down'},"
				"{'type':'touch','x':180,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':205,'y': 84,'state':'down'},"
				"{'type':'touch','x':205,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':229,'y': 85,'state':'down'},"
				"{'type':'touch','x':229,'y': 85,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':251,'y': 82,'state':'down'},"
				"{'type':'touch','x':251,'y': 82,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':275,'y': 84,'state':'down'},"
				"{'type':'touch','x':275,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':301,'y': 84,'state':'down'},"
				"{'type':'touch','x':301,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':326,'y': 83,'state':'down'},"
				"{'type':'touch','x':326,'y': 83,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':347,'y': 84,'state':'down'},"
				"{'type':'touch','x':347,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':371,'y': 82,'state':'down'},"
				"{'type':'touch','x':371,'y': 82,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':397,'y': 84,'state':'down'},"
				"{'type':'touch','x':397,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':421,'y': 84,'state':'down'},"
				"{'type':'touch','x':421,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':445,'y': 82,'state':'down'},"
				"{'type':'touch','x':445,'y': 82,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':468,'y': 83,'state':'down'},"
				"{'type':'touch','x':468,'y': 83,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':341,'y': 54,'state':'down'},"
				"{'type':'touch','x':341,'y': 54,'state':'up'},"
				"{'type':'touch','x': 12,'y': 84,'state':'down'},"
				"{'type':'touch','x': 12,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x': 36,'y': 85,'state':'down'},"
				"{'type':'touch','x': 36,'y': 85,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x': 60,'y': 83,'state':'down'},"
				"{'type':'touch','x': 60,'y': 83,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x': 83,'y': 84,'state':'down'},"
				"{'type':'touch','x': 83,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':108,'y': 84,'state':'down'},"
				"{'type':'touch','x':108,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':133,'y': 83,'state':'down'},"
				"{'type':'touch','x':133,'y': 83,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':156,'y': 85,'state':'down'},"
				"{'type':'touch','x':156,'y': 85,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':180,'y': 83,'state':'down'},"
				"{'type':'touch','x':180,'y': 83,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':205,'y': 83,'state':'down'},"
				"{'type':'touch','x':205,'y': 83,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':230,'y': 83,'state':'down'},"
				"{'type':'touch','x':230,'y': 83,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':254,'y': 83,'state':'down'},"
				"{'type':'touch','x':254,'y': 83,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':276,'y': 84,'state':'down'},"
				"{'type':'touch','x':276,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':299,'y': 85,'state':'down'},"
				"{'type':'touch','x':299,'y': 85,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':324,'y': 84,'state':'down'},"
				"{'type':'touch','x':324,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':349,'y': 84,'state':'down'},"
				"{'type':'touch','x':349,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':372,'y': 84,'state':'down'},"
				"{'type':'touch','x':372,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':397,'y': 83,'state':'down'},"
				"{'type':'touch','x':397,'y': 83,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':420,'y': 83,'state':'down'},"
				"{'type':'touch','x':420,'y': 83,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':442,'y': 84,'state':'down'},"
				"{'type':'touch','x':442,'y': 84,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"
				"{'type':'touch','x':466,'y': 83,'state':'down'},"
				"{'type':'touch','x':466,'y': 83,'state':'up'},"
				"{'type':'key','key':9208,'state':'down','modifier':''     ,'character':' '},"
				"{'type':'key','key':9208,'state':'up'  ,'modifier':''     ,'character':' '},"



				"{'type':'touch','x': 54,'y': 20,'state':'down'},"
				"{'type':'touch','x': 54,'y': 20,'state':'up'},"

				"{'type':'touch','x': 54,'y': 20,'state':'down'},"
				"{'type':'touch','x': 54,'y': 20,'state':'up'},"
			"]");
			UIManager::notifier()->start_script(script, "test/out/sample_%d.svg");
			{
				UIManager::styles()->style("pearl");
				UIManager::colors()->appearance("light");
				sample_icon_menu();
			}
		}
	}

	void test_unitary()
	{
		static bool done = false;

		if (done == false)
		{
			done = true;
#if _DEBUG
			MaskValidator::test();
			Entry::test(); 
			String::test();
			TextStream::test();
			Json::test();
			WidgetStyle::test();
#endif
		}
	}
}
