#include "pybind/pyberialdraw.hpp"
void bind_color(py::module& m) {
    py::enum_<berialdraw::Color>(m, "Color")
        .value("TRANSPARENT", berialdraw::Color::TRANSPARENT)
        .value("TRANSPARENT_MASK", berialdraw::Color::TRANSPARENT_MASK)
        
        // Theme colors
        .value("THEME_RED", berialdraw::Color::THEME_RED)
        .value("THEME_ORANGE", berialdraw::Color::THEME_ORANGE)
        .value("THEME_YELLOW", berialdraw::Color::THEME_YELLOW)
        .value("THEME_LIME", berialdraw::Color::THEME_LIME)
        .value("THEME_GREEN", berialdraw::Color::THEME_GREEN)
        .value("THEME_JADE", berialdraw::Color::THEME_JADE)
        .value("THEME_CYAN", berialdraw::Color::THEME_CYAN)
        .value("THEME_AZURE", berialdraw::Color::THEME_AZURE)
        .value("THEME_BLUE", berialdraw::Color::THEME_BLUE)
        .value("THEME_INDIGO", berialdraw::Color::THEME_INDIGO)
        .value("THEME_PURPLE", berialdraw::Color::THEME_PURPLE)
        .value("THEME_VIOLET", berialdraw::Color::THEME_VIOLET)
        .value("THEME_FUSHIA", berialdraw::Color::THEME_FUSHIA)
        .value("THEME_PINK", berialdraw::Color::THEME_PINK)
        .value("THEME_ROSEWOOD", berialdraw::Color::THEME_ROSEWOOD)
        .value("THEME_SAND", berialdraw::Color::THEME_SAND)
        .value("THEME_ASH", berialdraw::Color::THEME_ASH)
        .value("THEME_GRAY", berialdraw::Color::THEME_GRAY)
        .value("THEME_ZINC", berialdraw::Color::THEME_ZINC)
        .value("THEME_SLATE", berialdraw::Color::THEME_SLATE)
        
        // Predefined colors
        .value("SUCCESS_COLOR", berialdraw::Color::SUCCESS_COLOR)
        .value("ERROR_COLOR", berialdraw::Color::ERROR_COLOR)
        .value("WARNING_COLOR", berialdraw::Color::WARNING_COLOR)
        .value("INFO_COLOR", berialdraw::Color::INFO_COLOR)
        
        // Widget colors
        .value("LABEL_TEXT_COLOR", berialdraw::Color::LABEL_TEXT_COLOR)
        .value("BUTTON_COLOR", berialdraw::Color::BUTTON_COLOR)
        .value("BUTTON_BORDER_COLOR", berialdraw::Color::BUTTON_BORDER_COLOR)
        .value("BUTTON_TEXT_COLOR", berialdraw::Color::BUTTON_TEXT_COLOR)
        .value("BUTTON_FOCUS_COLOR", berialdraw::Color::BUTTON_FOCUS_COLOR)
        .value("CANVAS_COLOR", berialdraw::Color::CANVAS_COLOR)
        .value("EDIT_COLOR", berialdraw::Color::EDIT_COLOR)
        .value("EDIT_BORDER_COLOR", berialdraw::Color::EDIT_BORDER_COLOR)
        .value("EDIT_TEXT_COLOR", berialdraw::Color::EDIT_TEXT_COLOR)
        .value("EDIT_CURSOR_COLOR", berialdraw::Color::EDIT_CURSOR_COLOR)
        .value("EDIT_PLACE_HOLDER_COLOR", berialdraw::Color::EDIT_PLACE_HOLDER_COLOR)
        .value("EDIT_FOCUS_COLOR", berialdraw::Color::EDIT_FOCUS_COLOR)
        .value("EDIT_SELECT_COLOR", berialdraw::Color::EDIT_SELECT_COLOR)
        .value("ICON_BACK_COLOR", berialdraw::Color::ICON_BACK_COLOR)
        .value("ICON_BORDER_COLOR", berialdraw::Color::ICON_BORDER_COLOR)
        .value("ICON_TEXT_COLOR", berialdraw::Color::ICON_TEXT_COLOR)
        .value("ICON_COLOR", berialdraw::Color::ICON_COLOR)
        .value("ICON_FOCUS_COLOR", berialdraw::Color::ICON_FOCUS_COLOR)
        .value("SWITCH_BORDER_COLOR", berialdraw::Color::SWITCH_BORDER_COLOR)
        .value("SWITCH_ON_TRACK_COLOR", berialdraw::Color::SWITCH_ON_TRACK_COLOR)
        .value("SWITCH_OFF_TRACK_COLOR", berialdraw::Color::SWITCH_OFF_TRACK_COLOR)
        .value("SWITCH_THUMB_COLOR", berialdraw::Color::SWITCH_THUMB_COLOR)
        .value("SWITCH_FOCUS_COLOR", berialdraw::Color::SWITCH_FOCUS_COLOR)
        .value("SLIDER_BORDER_COLOR", berialdraw::Color::SLIDER_BORDER_COLOR)
        .value("SLIDER_TRACK_COLOR", berialdraw::Color::SLIDER_TRACK_COLOR)
        .value("SLIDER_HANDLE_COLOR", berialdraw::Color::SLIDER_HANDLE_COLOR)
        .value("SLIDER_FOCUS_COLOR", berialdraw::Color::SLIDER_FOCUS_COLOR)
        .value("PROGRESS_BAR_BORDER_COLOR", berialdraw::Color::PROGRESS_BAR_BORDER_COLOR)
        .value("PROGRESS_BAR_TRACK_COLOR", berialdraw::Color::PROGRESS_BAR_TRACK_COLOR)
        .value("PROGRESS_BAR_FILL_COLOR", berialdraw::Color::PROGRESS_BAR_FILL_COLOR)
        .value("PANE_COLOR", berialdraw::Color::PANE_COLOR)
        .value("PANE_BORDER_COLOR", berialdraw::Color::PANE_BORDER_COLOR)
        .value("KEYBOARD_KEY_COLOR", berialdraw::Color::KEYBOARD_KEY_COLOR)
        .value("KEYBOARD_KEY_BORDER_COLOR", berialdraw::Color::KEYBOARD_KEY_BORDER_COLOR)
        .value("KEYBOARD_KEY_TEXT_COLOR", berialdraw::Color::KEYBOARD_KEY_TEXT_COLOR)
        .value("KEYBOARD_FUNC_COLOR", berialdraw::Color::KEYBOARD_FUNC_COLOR)
        .value("KEYBOARD_FUNC_BORDER_COLOR", berialdraw::Color::KEYBOARD_FUNC_BORDER_COLOR)
        .value("KEYBOARD_FUNC_TEXT_COLOR", berialdraw::Color::KEYBOARD_FUNC_TEXT_COLOR)
        .value("WINDOW_COLOR", berialdraw::Color::WINDOW_COLOR)
        .value("SHAPE_COLOR", berialdraw::Color::SHAPE_COLOR)
        .value("HEADER_COLOR", berialdraw::Color::HEADER_COLOR)
        .value("HEADER_TEXT_COLOR", berialdraw::Color::HEADER_TEXT_COLOR)
        
        // Theme background colors
        .value("THEME_BACK_COLOR", berialdraw::Color::THEME_BACK_COLOR)
        .value("THEME_BACK_COLOR_LIGHT_1", berialdraw::Color::THEME_BACK_COLOR_LIGHT_1)
        .value("THEME_BACK_COLOR_LIGHT_2", berialdraw::Color::THEME_BACK_COLOR_LIGHT_2)
        .value("THEME_BACK_COLOR_LIGHT_3", berialdraw::Color::THEME_BACK_COLOR_LIGHT_3)
        .value("THEME_BACK_COLOR_LIGHT_4", berialdraw::Color::THEME_BACK_COLOR_LIGHT_4)
        .value("THEME_BACK_COLOR_LIGHT_5", berialdraw::Color::THEME_BACK_COLOR_LIGHT_5)
        .value("THEME_BACK_COLOR_LIGHT_6", berialdraw::Color::THEME_BACK_COLOR_LIGHT_6)
        .value("THEME_BACK_COLOR_LIGHT_7", berialdraw::Color::THEME_BACK_COLOR_LIGHT_7)
        .value("THEME_BACK_COLOR_LIGHT_8", berialdraw::Color::THEME_BACK_COLOR_LIGHT_8)
        .value("THEME_BACK_COLOR_LIGHT_9", berialdraw::Color::THEME_BACK_COLOR_LIGHT_9)
        .value("THEME_BACK_COLOR_LIGHT_10", berialdraw::Color::THEME_BACK_COLOR_LIGHT_10)
        .value("THEME_BACK_COLOR_LIGHT_11", berialdraw::Color::THEME_BACK_COLOR_LIGHT_11)
        .value("THEME_BACK_COLOR_LIGHT_12", berialdraw::Color::THEME_BACK_COLOR_LIGHT_12)
        .value("THEME_BACK_COLOR_LIGHT_13", berialdraw::Color::THEME_BACK_COLOR_LIGHT_13)
        .value("THEME_BACK_COLOR_LIGHT_14", berialdraw::Color::THEME_BACK_COLOR_LIGHT_14)
        .value("THEME_BACK_COLOR_LIGHT_15", berialdraw::Color::THEME_BACK_COLOR_LIGHT_15)
        
        .value("THEME_FORE_COLOR", berialdraw::Color::THEME_FORE_COLOR)
        .value("THEME_BACK_COLOR_DARK_1", berialdraw::Color::THEME_BACK_COLOR_DARK_1)
        .value("THEME_BACK_COLOR_DARK_2", berialdraw::Color::THEME_BACK_COLOR_DARK_2)
        .value("THEME_BACK_COLOR_DARK_3", berialdraw::Color::THEME_BACK_COLOR_DARK_3)
        .value("THEME_BACK_COLOR_DARK_4", berialdraw::Color::THEME_BACK_COLOR_DARK_4)
        .value("THEME_BACK_COLOR_DARK_5", berialdraw::Color::THEME_BACK_COLOR_DARK_5)
        .value("THEME_BACK_COLOR_DARK_6", berialdraw::Color::THEME_BACK_COLOR_DARK_6)
        .value("THEME_BACK_COLOR_DARK_7", berialdraw::Color::THEME_BACK_COLOR_DARK_7)
        .value("THEME_BACK_COLOR_DARK_8", berialdraw::Color::THEME_BACK_COLOR_DARK_8)
        .value("THEME_BACK_COLOR_DARK_9", berialdraw::Color::THEME_BACK_COLOR_DARK_9)
        .value("THEME_BACK_COLOR_DARK_10", berialdraw::Color::THEME_BACK_COLOR_DARK_10)
        .value("THEME_BACK_COLOR_DARK_11", berialdraw::Color::THEME_BACK_COLOR_DARK_11)
        .value("THEME_BACK_COLOR_DARK_12", berialdraw::Color::THEME_BACK_COLOR_DARK_12)
        .value("THEME_BACK_COLOR_DARK_13", berialdraw::Color::THEME_BACK_COLOR_DARK_13)
        .value("THEME_BACK_COLOR_DARK_14", berialdraw::Color::THEME_BACK_COLOR_DARK_14)
        .value("THEME_BACK_COLOR_DARK_15", berialdraw::Color::THEME_BACK_COLOR_DARK_15)
        
        // Standard colors (selection of the most common ones to avoid huge enum)
        .value("BLACK", berialdraw::Color::BLACK)
        .value("WHITE", berialdraw::Color::WHITE)
        .value("RED", berialdraw::Color::RED)
        .value("GREEN", berialdraw::Color::GREEN)
        .value("BLUE", berialdraw::Color::BLUE)
        .value("YELLOW", berialdraw::Color::YELLOW)
        .value("CYAN", berialdraw::Color::CYAN)
        .value("MAGENTA", berialdraw::Color::MAGENTA)
        .value("GRAY", berialdraw::Color::GRAY)
        .value("SILVER", berialdraw::Color::SILVER)
        .value("ORANGE", berialdraw::Color::ORANGE)
        .value("PURPLE", berialdraw::Color::PURPLE)
        .value("BROWN", berialdraw::Color::BROWN)
        .value("PINK", berialdraw::Color::PINK)
        .value("LIME", berialdraw::Color::LIME)
        .value("NAVY", berialdraw::Color::NAVY)
        .value("MAROON", berialdraw::Color::MAROON)
        .value("OLIVE", berialdraw::Color::OLIVE)
        .value("TEAL", berialdraw::Color::TEAL)
        .value("AQUA", berialdraw::Color::AQUA)
        .value("FUCHSIA", berialdraw::Color::FUCHSIA)
        .value("LIGHT_GRAY", berialdraw::Color::LIGHT_GRAY)
        .value("DARK_GRAY", berialdraw::Color::DARK_GRAY)
        .value("LIGHT_BLUE", berialdraw::Color::LIGHT_BLUE)
        .value("LIGHT_GREEN", berialdraw::Color::LIGHT_GREEN)
        .value("LIGHT_PINK", berialdraw::Color::LIGHT_PINK)
        .value("GOLD", berialdraw::Color::GOLD)
        .value("CRIMSON", berialdraw::Color::CRIMSON)
        .value("INDIGO", berialdraw::Color::INDIGO)
        .value("VIOLET", berialdraw::Color::VIOLET)
        .export_values();
}
